server:  
  port: ${PORT:8082}

eureka:  
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:9001}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
       
ribbon:
  eureka:
    enabled: true