node {

    withMaven(maven:'M3') {

        stage('Checkout') {
            git url: 'https://github.com/tuanhiep225/demo-microservice.git', branch: 'master'
        }
        
        
        stage('Build Images') {
            sh 'mvn clean package'
        }
        
        stage('Stop'){
            sh 'docker ps -f name=discovery -q | xargs --no-run-if-empty docker container stop'
            sh 'docker container ls -a -f name=discovery -q | xargs -r docker container rm'
        }
        
        stage ('Run') {
            docker.image("sodo/discovery-service").run('-p 9001:9001 -h discovery --name discovery')
        }

        stage ('Final') {
            build job: 'account-service-pipeline', wait: false
        }      

    }

}