server:  
  port: ${PORT:8081}

spring:  
  application:
    name: account-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
      
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:9001}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
---
spring:
  profiles: account-service-replica01
eureka:
  instance:
    appname: account-service  # ==> This is a instance of account-service
  client:   
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:9001}/eureka/  
server:
  port: 8083   
     
---
spring:
  profiles: account-service-replica02
eureka:
  instance:
    appname: account-service  # ==> This is a instance of account-service
  client:   
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:9001}/eureka/    
server:
  port: 8084

ribbon:
  eureka:
    enabled: true