node {

    withMaven(maven:'M3') {

        stage('Checkout') {
            git url: 'https://github.com/tuanhiep225/demo-microservice.git', branch: 'master'
        }

        stage('Build Images') {
            sh 'mvn clean package'
        }
        
        stage('Stop'){
            sh 'docker ps -f name=gateway -q | xargs --no-run-if-empty docker container stop'
            sh 'docker container ls -a -f name=gateway -q | xargs -r docker container rm'
        }


        stage ('Run') {
            docker.image("sodo/gateway-service").run('-p 9000:9000 -h gateway --name gateway --link discovery --link account --link customer')
        }
     

    }

}