node {

    withMaven(maven:'M3') {

        stage('Checkout') {
            git url: 'https://github.com/tuanhiep225/demo-microservice.git', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
        
        stage('Stop'){
            sh 'docker ps -f name=gateway -q | xargs --no-run-if-empty docker container stop'
            sh 'docker container ls -a -f name=gateway -q | xargs -r docker container rm'
        }


        stage('Image') {
            dir ('gateway-service') {
            	sh 'docker build -t sodo/gateway-service .'
            }
        }

        stage ('Run') {
        	sh 'docker run -d -p 9000:9000 -h gateway --name gateway --link discovery --link account --link customer sodo/gateway-service'
        }
     

    }

}