node {

    withMaven(maven:'M3') {

        stage('Checkout') {
            git url: 'https://github.com/tuanhiep225/demo-microservice.git', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
        stage('Stop'){
            sh 'docker ps -f name=account -q | xargs --no-run-if-empty docker container stop'
            sh 'docker container ls -a -f name=account -q | xargs -r docker container rm'
        }
        stage('Image') {
            dir ('account-service') {
            	sh 'docker build -t sodo/account-service .'
            }
        }

        stage ('Run') {
        	sh 'docker run -d -p 8081:8081 -h account --name account --link discovery sodo/account-service'
        }

        stage ('Final') {
            build job: 'customer-service-pipeline', wait: false
        }      

    }

}