node {

    withMaven(maven:'M3') {

        stage('Checkout') {
            git url: 'https://github.com/tuanhiep225/demo-microservice.git', branch: 'master'
        }


        stage('Build Images') {
            sh 'mvn clean package'
        }
        
        stage('Stop'){
            sh 'docker ps -f name=account -q | xargs --no-run-if-empty docker container stop'
            sh 'docker container ls -a -f name=account -q | xargs -r docker container rm'
        }

        stage ('Run') {
            docker.image("sodo/account-service").run('-p 8081:8081 -h account --name account --link discovery')
        }

        stage ('Final') {
            build job: 'customer-service-pipeline', wait: false
        }      

    }

}