node {

    withMaven(maven:'M3') {

        stage('Checkout') {
            git url: 'https://github.com/tuanhiep225/demo-microservice.git', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
        
        stage('Stop'){
            sh 'docker ps -f name=customer -q | xargs --no-run-if-empty docker container stop'
            sh 'docker container ls -a -f name=customer -q | xargs -r docker container rm'
        }

        stage('Image') {
            dir ('customer-service') {
                def app = docker.build "localhost:5000/customer-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/customer-service:${env.version}").run('-p 8085:8085 -h customer --name customer --link discovery --link account')
        }

        stage ('Final') {
            build job: 'gateway-service-pipeline', wait: false
        }      

    }

}