node {

    withMaven(maven:'M3') {

        stage('Checkout') {
            git url: 'https://github.com/tuanhiep225/demo-microservice.git', branch: 'master'
        }

        stage('Build Images') {
            sh 'mvn clean package'
        }
        
        stage('Stop'){
            sh 'docker ps -f name=customer -q | xargs --no-run-if-empty docker container stop'
            sh 'docker container ls -a -f name=customer -q | xargs -r docker container rm'
        }


        stage ('Run') {
            docker.image("sodo/customer-service").run('-p 8085:8085 -h customer --name customer --link discovery --link account')
        }

        stage ('Final') {
            build job: 'gateway-service-pipeline', wait: false
        }      

    }

}